version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: MiniTwit.Api/Dockerfile
    ports:
      - "5000:80"
    volumes:
      - ./MiniTwit.Api/Infrastructure:/app/Infrastructure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  client:
    build:
      context: .                 # <--- The entire solution is the build context
      dockerfile: MiniTwit.Client/Dockerfile
    ports:
      - "5001:80"

  simulator:
    build:
      context: ./Simulator
      dockerfile: Dockerfile
    environment:
      - SIMULATOR_HOST=http://api:80
