version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: MiniTwit.Api/Dockerfile
    ports:
      - "5000:80"         # Host port 5000 → container port 80 (HTTP)
    volumes:
      - ./MiniTwit.Api/Infrastructure:/app/Infrastructure
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80

  client:
    build:
      context: .
      dockerfile: MiniTwit.Client/Dockerfile
    ports:
      - "5001:80"         # Host port 5001 → container port 80 (Nginx serving the Blazor client)

  simulator:
    build:
      context: ./Simulator
      dockerfile: Dockerfile
    environment:
      - SIMULATOR_HOST=http://api:80   # Use the service name 'api' to reach the API container on port 80
