services:
  db:
    image: postgres:15-alpine
    container_name: minitwit_db
    restart: always
    environment:
      POSTGRES_DB: MiniTwitDb
      POSTGRES_USER: ${MINITWIT_DB_USER}
      POSTGRES_PASSWORD: ${MINITWIT_DB_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${MINITWIT_DB_USER}", "-d", "MiniTwitDb"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - published: 5433
        target: 5432

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.migrator
    # Wait for the database to be healthy
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=MiniTwitDb;Username=${MINITWIT_DB_USER};Password=${MINITWIT_DB_PASSWORD}
      ClientBaseUrl: https://whatever-url-or-placeholder # value must be set before it can build, but only api uses it
    # Mark migrator healthy only after /tmp/migrations_done is created
    healthcheck:
      test: ["CMD", "test", "-f", "/tmp/migrations_done"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 40s
      
  seq:
    image: datalust/seq:2024.3
    container_name: seq
    restart: always
    environment:
      ACCEPT_EULA: "Y"
    ports:
      - published: 5341
        target: 80
      
  api:
    build:
      context: .
      dockerfile: MiniTwit.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=MiniTwitDb;Username=${MINITWIT_DB_USER};Password=${MINITWIT_DB_PASSWORD}
    # IMPORTANT: Wait for db (healthy) and migrator (healthy)
    depends_on:
      db:
        condition: service_healthy
      migrator:
        condition: service_healthy
      seq:
        condition: service_started
    ports:
      - published: 5002
        target: 8080

  client:
    build:
      context: .
      dockerfile: MiniTwit.Client/Dockerfile
    ports:
      - published: 5001
        target: 80
