# Use a minimal base image (your bundle is self-contained)
FROM alpine:3.18
WORKDIR /app

COPY ef-migrations-bundle /app/ef-migrations-bundle

COPY appsettings.json /app/MiniTwit.Api/appsettings.json

RUN chmod +x /app/ef-migrations-bundle

ENTRYPOINT ["/app/ef-migrations-bundle"]
