# This is a basic workflow to help you get started with the GitHub Auto-Release on Commit Action.
# Credit to https://github.com/marketplace/actions/auto-release

name: AutoRelease

on:
  push:
    branches:
      - main
      - master

# permission to create a release
permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  release:
    # The type of runner that the job will run on
    runs-on: ubuntu-24.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v4
      - uses: CupOfTea696/gh-action-auto-release@v1.0.2
        with:
          title: "Release: $version"
          # use tag: vx.y (x.y defined below)
          tag: "v$version"
          draft: false
          # match Release: x.y (x and y being numbers). It must be at the start of a line, but it is not case sensitive
          regex: '/^Release: (?<version>[0-9]+\.[0-9]+)/i'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
