name: Build and Test

on:
  push:
    branches:
      - main
      - master
    paths-ignore:
      - '*.md'
  pull_request:
    branches:
      - main
    paths-ignore:
      - '*.md'
  workflow_dispatch:

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 9.0.x
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore MiniTwitSolution/MiniTwitSolution.sln

      - name: Build solution
        run: dotnet build MiniTwitSolution/MiniTwitSolution.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test MiniTwitSolution/MiniTwitSolution.sln --collect:"XPlat Code Coverage"

      - name: Generate Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: MiniTwitSolution/MiniTwit.Test/TestResults/**/coverage.cobertura.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: "20 80"

      - name: Send coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "MiniTwitSolution/MiniTwit.Test/TestResults/**/coverage.cobertura.xml"

      - name: Write Coverage Summary to Job
        run: cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
