name: Generate Report PDF

on:
  pull_request:
    branches:
      - main

jobs:
  build-report:
    runs-on: ubuntu-latest-24.04
    steps:
      - uses: actions/checkout@v4

      # Compile LaTeX to report/main.pdf
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: report/main.tex

      - name: Move PDF into build folder
        run: mv report/main.pdf report/build/MSc_group_j.pdf

      - name: Commit and push
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add report/build/MSc_group_j.pdf
          # continue only if changes are made
          git diff --cached --quiet || (
            git commit -m "Generate report"
            git pull --rebase origin ${{ github.head_ref }}
            git push origin HEAD:${{ github.head_ref }}
          )
